services:
  mqtt:
    image: eclipse-mosquitto:2.1.2-alpine
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - ./configs/mosquitto:/mosquitto/config
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log

volumes:
  mqtt-data:
  mqtt-log: