services:
  mqtt:
    image: eclipse-mosquitto:2.1.2-alpine
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - ./configs/mosquitto:/mosquitto/config
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
  pg_db:
    image: postgres:18.2
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - configs/postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql
  ingest:
    image: chiaf1/iot-nonna-ingest:1
    restart: unless-stopped
    volumes:
      - ./configs/ingest/config.yaml:/app/config.yaml
    depends_on:
      - mqtt
      - pg_db
  core:
    image: chiaf1/iot-nonna-core:1
    restart: unless-stopped
    ports:
      - 3030:3030
    volumes:
      - ./configs/core/config.yaml:/app/config.yaml
    depends_on:
      - pg_db
    environment:
      - RUN_MIGRATIONS=true
      - RUN_SEEDING=true
  frontend:
    image: chiaf1/iot-nonna-frontend:1
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - core
    environment:
      - API_URL=http://core:3030
volumes:
  mqtt-data:
  mqtt-log:
  pgdata: