services:
  mqtt:
    image: eclipse-mosquitto:2.1.2-alpine
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - ./configs/mosquitto:/mosquitto/config
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
  pg_db:
    image: postgres:18.2
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - configs/postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql
  ingest:
    image: chiaf1/iot-nonna-ingest:1
    restart: unless-stopped
    volumes:
      - ./configs/ingest/config.yaml:./config.yaml
    depends_on:
      - mqtt
      - pg_db
volumes:
  mqtt-data:
  mqtt-log:
  pgdata: